version: '2'
services:
    content-server:
        image: gpupo/content-repository-server
        ports:
            - 8080:8080
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
          - $PWD/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
          - $PWD/config/nginx/htpasswd.conf:/etc/nginx/htpasswd.conf
          - $PWD/var/jackrabbit:/opt/jackrabbit
        environment:
          - VIRTUAL_HOST=${VIRTUAL_HOST}
    php:
        image: gpupo/container-orchestration:php-fpm
        volumes:
          - $PWD/:/var/www/app
