version: '3.3'
services:
    content-server:
        image: gpupo/content-repository-server
        ports:
            - 8080:8080
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
          - $PWD/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
          - $PWD/config/nginx/htpasswd.conf:/etc/nginx/htpasswd.conf
          - jackrabbit-storage:/opt/jackrabbit
        environment:
          - VIRTUAL_HOST=${VIRTUAL_HOST}
        links:
          - content-server
    php:
        image: gpupo/container-orchestration:php-dev
        volumes:
          - $PWD/:/var/www/app
        command: echo "byes"
        links:
          - content-server
    java:
        image: openjdk:slim
        volumes:
          - $PWD/:/usr/src/myapp
        command: echo "bye"
        working_dir: /usr/src/myapp
        links:
          - content-server
volumes:
    jackrabbit-storage:
