version: '3.3'
services:
    content-server:
        image: gpupo/content-repository-server
        ports:
            - '${JACKRABBIT_PORT:-8080}:8080'
        volumes:
          - jackrabbit-storage:/opt/jackrabbit
        networks:
            - backend
    nginx:
        image: nginx:latest
        expose:
            - 80
        volumes:
          - $PWD/config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - $PWD/config/nginx/nginx.conf:/etc/nginx/nginx.conf
          - $PWD/config/nginx/htpasswd.conf:/etc/nginx/htpasswd.conf
          - $PWD/public:/usr/share/nginx/html
        environment:
            - VIRTUAL_HOST=${NGINX_CNAME}
            - VIRTUAL_PORT=80
        links:
            - content-server
        networks:
            - default
            - backend
    php-fpm:
        image: gpupo/container-orchestration:php-dev
        volumes:
            - $PWD/:/var/www/app
        links:
            - content-server
        networks:
            - backend
    java:
        image: openjdk:slim
        volumes:
            - $PWD/:/usr/src/myapp
        command: echo "bye"
        working_dir: /usr/src/myapp
        links:
            - content-server
        networks:
            - backend
volumes:
    jackrabbit-storage:
networks:
    default:
        external:
            name: nginx-proxy
    backend: ~
