version: '3.3'
services:
    php-fpm:
        image: gpupo/container-orchestration:php-dev
        volumes:
          - $PWD/:/var/www/app
        links:
          - content-server
        networks:
            - backend
    java:
        image: openjdk:slim
        volumes:
          - $PWD/:/usr/src/myapp
        command: echo "bye"
        working_dir: /usr/src/myapp
        links:
          - content-server
        networks:
            - backend
