name: CI
on:
  pull_request:
    branches:
      - master
      - develop
      - verbose
    paths-ignore:
      - '**.md'
      - 'examples/**'
  push:
    branches:
      - master
      - develop
      - verbose
    paths-ignore:
      - '**.md'
      - 'examples/**'
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Host Prepare
        run: sudo -- sh -c "echo 127.0.0.1	static.localhost content-server >> /etc/hosts"

      - name: Httpd Gateway prepare
        run: git clone https://github.com/gpupo/httpd-gateway.git && pushd httpd-gateway && make setup && make alone && popd;

      - name: Docker Compose prepare
        run: docker network create nginx-proxy && docker compose up -d

      - name: Setup
        run: make install && make demo && echo 'JACKRABBIT_SERVER=localhost' >> .env.test

      - name: Run test suite
        run: APP_ENV=test vendor/bin/phpunit
